In [1]:
import pandas as pd
import numpy as np
import scipy
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
print(np.log(22))
print(np.__version__)

3.091042453358316
1.26.2


In [3]:
num1=[1,2,3,4]
num2=[3,4,5,6]

num1+num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [4]:
arr1=np.array(num1)
arr2=np.array(num2)

arr1+arr2

array([ 4,  6,  8, 10])

In [5]:
arr=np.array([1,np.e,np.e**2,10])

print('원래 배열',arr)
print('자연로그 배열',np.log(arr))

원래 배열 [ 1.          2.71828183  7.3890561  10.        ]
자연로그 배열 [0.         1.         2.         2.30258509]


In [6]:
data1=[0,1,2,3,4,5]
a1=np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [7]:
a1.dtype 
#int8,int16,int32,int64 -> 메모리관리

dtype('int32')

In [8]:
data2=[0.5,2.0,0.1,8]
a2=np.array(data2)
a2

array([0.5, 2. , 0.1, 8. ])

In [9]:
a2.dtype

dtype('float64')

## numpy 배열 생성
- 1차원,2차원,3차원.. 배열생성 가능

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
b1=np.arange(12).reshape(2,2,3)
b1.shape

(2, 2, 3)

In [14]:
arr5=np.linspace(0,20,5)
arr5.dtype

dtype('float64')

In [15]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
#단위행렬
arr_I=np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr=np.array(['1.5','0.62'])
num_arr=arr.astype(float)
num_arr.dtype

dtype('float64')

In [19]:
num_f1=np.array([10,21,0.549,4.75,5.98])
num_f1=num_f1.astype(int) #소수점 삭제
num_f1

array([10, 21,  0,  4,  5])

In [20]:
num_f1=np.array([10,21,0.549,4.75,5.98])
num_f1=num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [21]:
np.random.rand(2,3) #0~1 사이의 난수 배열(n,m)

array([[0.38068978, 0.06483642, 0.47670918],
       [0.47499787, 0.31777825, 0.04494895]])

In [22]:
np.random.randint(2,10) #n~m까지의 정수 랜덤

5

In [23]:
a=np.random.choice(np.arange(1, 46), size=6, replace=False)
a.sort()
a

array([ 8,  9, 11, 20, 38, 41])

In [12]:
list_a=[]
while len(list_a)<7:
    b=np.random.randint(1,46)
    if b in list_a:
        pass
    else:
        list_a.append(b)
list_a

[33, 23, 8, 13, 24, 6, 7]

In [22]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


## 비교연산

In [31]:
arr1=np.array([10,20,30,40])
for i in range(len(arr1)):
    if arr1[i]>20:
        arr1[i]=0
    else:
        arr1[i]=1

In [32]:
arr1

array([1, 1, 0, 0])

## 등계연산
- Numpy 합 평균 표준편차 분산 최솟값 최댓값 등 메서드 존재
  + 기술 통계량

In [36]:
arr3=np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [42]:
print(arr3.sum())
print(arr3.mean())
print(arr3.var())
print(arr3.max())
print(arr3.min())
print(arr3.std())

10
2.0
2.0
4
0
1.4142135623730951


## 누적합 누적곱

In [47]:
arr4=np.arange(1,5)

In [48]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [49]:
arr4.cumsum()

array([ 1,  3,  6, 10])

## 행렬연산
- 선형대수를 위한 2차원 배열 연산도 지원

In [55]:
A=np.array([0,1,2,3]).reshape(2,2)
B=np.array([3,2,0,1]).reshape(2,2)

In [56]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [57]:
A

array([[0, 1],
       [2, 3]])

In [58]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [60]:
np.linalg.inv(A).dot(A)

array([[1., 0.],
       [0., 1.]])

## 배열의 인덱싱 슬라이싱

In [65]:
a1=np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [66]:
a1[5]

50

In [69]:
a1[[0,2,4]]

array([ 0, 20, 40])

In [81]:
a2=np.arange(10,106,5).reshape(4,5)

In [82]:
a2

array([[ 10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80],
       [ 85,  90,  95, 100, 105]])

In [88]:
a2[1:3,1:4]

array([[40, 45, 50],
       [65, 70, 75]])

In [89]:
a2[0]

array([10, 15, 20, 25, 30])

In [92]:
a2[[0,2],[1,1]]

array([15, 65])

## 배열 조건문
- pandas 와 유사

In [93]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [96]:
for i in range(len(a)):
    if a[i]>3:
        print(a[i])

4
5
6


In [101]:
a[a%2==0]

array([2, 4, 6])

In [102]:
a>3

array([False, False, False,  True,  True,  True])

In [103]:
b1=np.array([0,1,2,3,4,5])
b1

array([0, 1, 2, 3, 4, 5])

In [104]:
b1[1:4]

array([1, 2, 3])

In [105]:
b1[2:]

array([2, 3, 4, 5])

In [107]:
b1[0:4:2]

array([0, 2])

In [108]:
b1[2:5]=np.array([25,35,45])

In [109]:
b1

array([ 0,  1, 25, 35, 45,  5])

In [110]:
b1[3:6]=60
b1

array([ 0,  1, 25, 60, 60, 60])

In [111]:
a2[1]

array([35, 40, 45, 50, 55])

In [112]:
a2[1][1]

40

## numpy 조건문
- np.where
- np.select 

In [114]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.where(arr<5,arr,arr*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [116]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
# 100,101,2,3,4,5,12,14,16,18
cond_list=[arr>5,arr<2]
choice_list=[arr*2,arr+100]
np.select(cond_list,choice_list,arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])